//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更此檔案可能會導致不正確的行為，而且若已重新產生
//     程式碼，則會遺失變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendNowServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SendNowServiceReference.SendNowSoap")]
    public interface SendNowSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendToOne", ReplyAction="*")]
        System.Threading.Tasks.Task<SendNowServiceReference.SendToOneResponse> SendToOneAsync(SendNowServiceReference.SendToOneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendNowAPIWithReplyName", ReplyAction="*")]
        System.Threading.Tasks.Task<SendNowServiceReference.SendNowAPIWithReplyNameResponse> SendNowAPIWithReplyNameAsync(SendNowServiceReference.SendNowAPIWithReplyNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendNowAPI", ReplyAction="*")]
        System.Threading.Tasks.Task<SendNowServiceReference.SendNowAPIResponse> SendNowAPIAsync(SendNowServiceReference.SendNowAPIRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendToOneRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendToOne", Namespace="http://tempuri.org/", Order=0)]
        public SendNowServiceReference.SendToOneRequestBody Body;
        
        public SendToOneRequest()
        {
        }
        
        public SendToOneRequest(SendNowServiceReference.SendToOneRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendToOneRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string project_category_code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string toname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string toemail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string fromname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string fromemail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string content;
        
        public SendToOneRequestBody()
        {
        }
        
        public SendToOneRequestBody(string project_category_code, string toname, string toemail, string fromname, string fromemail, string subject, string content)
        {
            this.project_category_code = project_category_code;
            this.toname = toname;
            this.toemail = toemail;
            this.fromname = fromname;
            this.fromemail = fromemail;
            this.subject = subject;
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendToOneResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendToOneResponse", Namespace="http://tempuri.org/", Order=0)]
        public SendNowServiceReference.SendToOneResponseBody Body;
        
        public SendToOneResponse()
        {
        }
        
        public SendToOneResponse(SendNowServiceReference.SendToOneResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendToOneResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendToOneResult;
        
        public SendToOneResponseBody()
        {
        }
        
        public SendToOneResponseBody(bool SendToOneResult)
        {
            this.SendToOneResult = SendToOneResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendNowAPIWithReplyNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendNowAPIWithReplyName", Namespace="http://tempuri.org/", Order=0)]
        public SendNowServiceReference.SendNowAPIWithReplyNameRequestBody Body;
        
        public SendNowAPIWithReplyNameRequest()
        {
        }
        
        public SendNowAPIWithReplyNameRequest(SendNowServiceReference.SendNowAPIWithReplyNameRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendNowAPIWithReplyNameRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string project_category_code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string toname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string toemail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string fromname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string fromemail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Channel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string PGCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string CustID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public byte[] attach_file_stream_1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string file_name_1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public byte[] attach_file_stream_2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string file_name_2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public byte[] attach_file_stream_3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string file_name_3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public byte[] attach_file_stream_4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string file_name_4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public byte[] attach_file_stream_5;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string file_name_5;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string replyemail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string priority;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string replyname;
        
        public SendNowAPIWithReplyNameRequestBody()
        {
        }
        
        public SendNowAPIWithReplyNameRequestBody(
                    string project_category_code, 
                    string toname, 
                    string toemail, 
                    string fromname, 
                    string fromemail, 
                    string subject, 
                    string content, 
                    string Channel, 
                    string PGCode, 
                    string CustID, 
                    byte[] attach_file_stream_1, 
                    string file_name_1, 
                    byte[] attach_file_stream_2, 
                    string file_name_2, 
                    byte[] attach_file_stream_3, 
                    string file_name_3, 
                    byte[] attach_file_stream_4, 
                    string file_name_4, 
                    byte[] attach_file_stream_5, 
                    string file_name_5, 
                    string replyemail, 
                    string priority, 
                    string replyname)
        {
            this.project_category_code = project_category_code;
            this.toname = toname;
            this.toemail = toemail;
            this.fromname = fromname;
            this.fromemail = fromemail;
            this.subject = subject;
            this.content = content;
            this.Channel = Channel;
            this.PGCode = PGCode;
            this.CustID = CustID;
            this.attach_file_stream_1 = attach_file_stream_1;
            this.file_name_1 = file_name_1;
            this.attach_file_stream_2 = attach_file_stream_2;
            this.file_name_2 = file_name_2;
            this.attach_file_stream_3 = attach_file_stream_3;
            this.file_name_3 = file_name_3;
            this.attach_file_stream_4 = attach_file_stream_4;
            this.file_name_4 = file_name_4;
            this.attach_file_stream_5 = attach_file_stream_5;
            this.file_name_5 = file_name_5;
            this.replyemail = replyemail;
            this.priority = priority;
            this.replyname = replyname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendNowAPIWithReplyNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendNowAPIWithReplyNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public SendNowServiceReference.SendNowAPIWithReplyNameResponseBody Body;
        
        public SendNowAPIWithReplyNameResponse()
        {
        }
        
        public SendNowAPIWithReplyNameResponse(SendNowServiceReference.SendNowAPIWithReplyNameResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendNowAPIWithReplyNameResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendNowAPIWithReplyNameResult;
        
        public SendNowAPIWithReplyNameResponseBody()
        {
        }
        
        public SendNowAPIWithReplyNameResponseBody(bool SendNowAPIWithReplyNameResult)
        {
            this.SendNowAPIWithReplyNameResult = SendNowAPIWithReplyNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendNowAPIRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendNowAPI", Namespace="http://tempuri.org/", Order=0)]
        public SendNowServiceReference.SendNowAPIRequestBody Body;
        
        public SendNowAPIRequest()
        {
        }
        
        public SendNowAPIRequest(SendNowServiceReference.SendNowAPIRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendNowAPIRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string project_category_code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string toname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string toemail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string fromname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string fromemail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Channel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string PGCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string CustID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public byte[] attach_file_stream_1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string file_name_1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public byte[] attach_file_stream_2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string file_name_2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public byte[] attach_file_stream_3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string file_name_3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public byte[] attach_file_stream_4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string file_name_4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public byte[] attach_file_stream_5;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string file_name_5;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string replyemail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string priority;
        
        public SendNowAPIRequestBody()
        {
        }
        
        public SendNowAPIRequestBody(
                    string project_category_code, 
                    string toname, 
                    string toemail, 
                    string fromname, 
                    string fromemail, 
                    string subject, 
                    string content, 
                    string Channel, 
                    string PGCode, 
                    string CustID, 
                    byte[] attach_file_stream_1, 
                    string file_name_1, 
                    byte[] attach_file_stream_2, 
                    string file_name_2, 
                    byte[] attach_file_stream_3, 
                    string file_name_3, 
                    byte[] attach_file_stream_4, 
                    string file_name_4, 
                    byte[] attach_file_stream_5, 
                    string file_name_5, 
                    string replyemail, 
                    string priority)
        {
            this.project_category_code = project_category_code;
            this.toname = toname;
            this.toemail = toemail;
            this.fromname = fromname;
            this.fromemail = fromemail;
            this.subject = subject;
            this.content = content;
            this.Channel = Channel;
            this.PGCode = PGCode;
            this.CustID = CustID;
            this.attach_file_stream_1 = attach_file_stream_1;
            this.file_name_1 = file_name_1;
            this.attach_file_stream_2 = attach_file_stream_2;
            this.file_name_2 = file_name_2;
            this.attach_file_stream_3 = attach_file_stream_3;
            this.file_name_3 = file_name_3;
            this.attach_file_stream_4 = attach_file_stream_4;
            this.file_name_4 = file_name_4;
            this.attach_file_stream_5 = attach_file_stream_5;
            this.file_name_5 = file_name_5;
            this.replyemail = replyemail;
            this.priority = priority;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendNowAPIResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendNowAPIResponse", Namespace="http://tempuri.org/", Order=0)]
        public SendNowServiceReference.SendNowAPIResponseBody Body;
        
        public SendNowAPIResponse()
        {
        }
        
        public SendNowAPIResponse(SendNowServiceReference.SendNowAPIResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendNowAPIResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendNowAPIResult;
        
        public SendNowAPIResponseBody()
        {
        }
        
        public SendNowAPIResponseBody(bool SendNowAPIResult)
        {
            this.SendNowAPIResult = SendNowAPIResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface SendNowSoapChannel : SendNowServiceReference.SendNowSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class SendNowSoapClient : System.ServiceModel.ClientBase<SendNowServiceReference.SendNowSoap>, SendNowServiceReference.SendNowSoap
    {
        
        /// <summary>
        /// 實作此部分方法來設定服務端點。
        /// </summary>
        /// <param name="serviceEndpoint">要設定的端點</param>
        /// <param name="clientCredentials">用戶端認證</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SendNowSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SendNowSoapClient.GetBindingForEndpoint(endpointConfiguration), SendNowSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendNowSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SendNowSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendNowSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SendNowSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendNowSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendNowServiceReference.SendToOneResponse> SendNowServiceReference.SendNowSoap.SendToOneAsync(SendNowServiceReference.SendToOneRequest request)
        {
            return base.Channel.SendToOneAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendNowServiceReference.SendToOneResponse> SendToOneAsync(string project_category_code, string toname, string toemail, string fromname, string fromemail, string subject, string content)
        {
            SendNowServiceReference.SendToOneRequest inValue = new SendNowServiceReference.SendToOneRequest();
            inValue.Body = new SendNowServiceReference.SendToOneRequestBody();
            inValue.Body.project_category_code = project_category_code;
            inValue.Body.toname = toname;
            inValue.Body.toemail = toemail;
            inValue.Body.fromname = fromname;
            inValue.Body.fromemail = fromemail;
            inValue.Body.subject = subject;
            inValue.Body.content = content;
            return ((SendNowServiceReference.SendNowSoap)(this)).SendToOneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendNowServiceReference.SendNowAPIWithReplyNameResponse> SendNowServiceReference.SendNowSoap.SendNowAPIWithReplyNameAsync(SendNowServiceReference.SendNowAPIWithReplyNameRequest request)
        {
            return base.Channel.SendNowAPIWithReplyNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendNowServiceReference.SendNowAPIWithReplyNameResponse> SendNowAPIWithReplyNameAsync(
                    string project_category_code, 
                    string toname, 
                    string toemail, 
                    string fromname, 
                    string fromemail, 
                    string subject, 
                    string content, 
                    string Channel, 
                    string PGCode, 
                    string CustID, 
                    byte[] attach_file_stream_1, 
                    string file_name_1, 
                    byte[] attach_file_stream_2, 
                    string file_name_2, 
                    byte[] attach_file_stream_3, 
                    string file_name_3, 
                    byte[] attach_file_stream_4, 
                    string file_name_4, 
                    byte[] attach_file_stream_5, 
                    string file_name_5, 
                    string replyemail, 
                    string priority, 
                    string replyname)
        {
            SendNowServiceReference.SendNowAPIWithReplyNameRequest inValue = new SendNowServiceReference.SendNowAPIWithReplyNameRequest();
            inValue.Body = new SendNowServiceReference.SendNowAPIWithReplyNameRequestBody();
            inValue.Body.project_category_code = project_category_code;
            inValue.Body.toname = toname;
            inValue.Body.toemail = toemail;
            inValue.Body.fromname = fromname;
            inValue.Body.fromemail = fromemail;
            inValue.Body.subject = subject;
            inValue.Body.content = content;
            inValue.Body.Channel = Channel;
            inValue.Body.PGCode = PGCode;
            inValue.Body.CustID = CustID;
            inValue.Body.attach_file_stream_1 = attach_file_stream_1;
            inValue.Body.file_name_1 = file_name_1;
            inValue.Body.attach_file_stream_2 = attach_file_stream_2;
            inValue.Body.file_name_2 = file_name_2;
            inValue.Body.attach_file_stream_3 = attach_file_stream_3;
            inValue.Body.file_name_3 = file_name_3;
            inValue.Body.attach_file_stream_4 = attach_file_stream_4;
            inValue.Body.file_name_4 = file_name_4;
            inValue.Body.attach_file_stream_5 = attach_file_stream_5;
            inValue.Body.file_name_5 = file_name_5;
            inValue.Body.replyemail = replyemail;
            inValue.Body.priority = priority;
            inValue.Body.replyname = replyname;
            return ((SendNowServiceReference.SendNowSoap)(this)).SendNowAPIWithReplyNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendNowServiceReference.SendNowAPIResponse> SendNowServiceReference.SendNowSoap.SendNowAPIAsync(SendNowServiceReference.SendNowAPIRequest request)
        {
            return base.Channel.SendNowAPIAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendNowServiceReference.SendNowAPIResponse> SendNowAPIAsync(
                    string project_category_code, 
                    string toname, 
                    string toemail, 
                    string fromname, 
                    string fromemail, 
                    string subject, 
                    string content, 
                    string Channel, 
                    string PGCode, 
                    string CustID, 
                    byte[] attach_file_stream_1, 
                    string file_name_1, 
                    byte[] attach_file_stream_2, 
                    string file_name_2, 
                    byte[] attach_file_stream_3, 
                    string file_name_3, 
                    byte[] attach_file_stream_4, 
                    string file_name_4, 
                    byte[] attach_file_stream_5, 
                    string file_name_5, 
                    string replyemail, 
                    string priority)
        {
            SendNowServiceReference.SendNowAPIRequest inValue = new SendNowServiceReference.SendNowAPIRequest();
            inValue.Body = new SendNowServiceReference.SendNowAPIRequestBody();
            inValue.Body.project_category_code = project_category_code;
            inValue.Body.toname = toname;
            inValue.Body.toemail = toemail;
            inValue.Body.fromname = fromname;
            inValue.Body.fromemail = fromemail;
            inValue.Body.subject = subject;
            inValue.Body.content = content;
            inValue.Body.Channel = Channel;
            inValue.Body.PGCode = PGCode;
            inValue.Body.CustID = CustID;
            inValue.Body.attach_file_stream_1 = attach_file_stream_1;
            inValue.Body.file_name_1 = file_name_1;
            inValue.Body.attach_file_stream_2 = attach_file_stream_2;
            inValue.Body.file_name_2 = file_name_2;
            inValue.Body.attach_file_stream_3 = attach_file_stream_3;
            inValue.Body.file_name_3 = file_name_3;
            inValue.Body.attach_file_stream_4 = attach_file_stream_4;
            inValue.Body.file_name_4 = file_name_4;
            inValue.Body.attach_file_stream_5 = attach_file_stream_5;
            inValue.Body.file_name_5 = file_name_5;
            inValue.Body.replyemail = replyemail;
            inValue.Body.priority = priority;
            return ((SendNowServiceReference.SendNowSoap)(this)).SendNowAPIAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SendNowSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SendNowSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名為 \'{0}\' 的端點。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SendNowSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://10.11.37.45/Mailhunter_api/SendNow.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SendNowSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://10.11.37.45/Mailhunter_api/SendNow.asmx");
            }
            throw new System.InvalidOperationException(string.Format("找不到名為 \'{0}\' 的端點。", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SendNowSoap,
            
            SendNowSoap12,
        }
    }
}
